### ISSUE TITLE
I have modules that do not export es6 style but need to be transformed

### ISSUE THREAD

**Issue by elevatebart** [monounity/karma-typescript-es6-transform#1]
Why limit the transforms to files that contain import and exports ES6 style like so ?
```js
if(isEs6(context.js.ast)){
    ...
}
```
Why not simply babel every file ?
I am trying to use the [delay](https://www.npmjs.com/package/delay) library in a Karma-Typescript context and the testing returns a parsing error at bundling even with your transform.

Can you help me figure it out ?

**Comment by erikbarke** [comment]
Hey @elevatebart, I'll take a look!

**Comment by elevatebart** [comment]
I was even nicer, I created a pull request #2.
Hope you like it ;-)

**Comment by erikbarke** [comment]
Thanks!! Unfortunately #2 broke a lot of things including the integration tests in `karma-typescript`...  I've improved the ES6 detection by looking for more keywords recursively and I have a successful integration test in `karma-typescript` locally that requires the `delay` module.

Does it work for you too if you install the latest from master, `npm i github:monounity/karma-typescript-es6-transform`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by elevatebart** [comment]
Do you know where I could have access to these integration tests so that I can make sure that my branch does not break them before I go ahead and submit anything else. The first issue with [delay](https://www.npmjs.com/package/delay) was the use of an arrow expression ```() => 'the return';```

**Comment by elevatebart** [comment]
Just to be clear, your changes fixed my initial issue which was to be able to use 'delay'.
But if the module I import from npm is built as follows
``` js
module.export = () => {
    return "test";
}
```
the bundling will probably fail.

**Comment by erikbarke** [comment]
Ok, I've added support for fat arrow functions too with a unit test containing your example!
Also, the integration tests are referenced above if you want to take a look.
Thanks for reporting this and coming up with suggestions 😃

**Comment by elevatebart** [comment]
it's working like a charm !!! thank you !!!

**Comment by elevatebart** [comment]
We tested it on our side and we love it. The last thing we need is ```npm publish``` and we are all set !!!
Do not forget to increase the minor package number ;-).

Once this is done, you can close the issue.

**Comment by erikbarke** [comment]
On npm now!
